@startuml

[*] --> FreeState

state FreeState : 自由态
state ContinuousState : 连携态

state MidThrust1 : 中段1
state MidThrust2 : 中段2
state MidThrust3 : 中段3

state MHighThrust1 : 上段1
state MHighThrust2 : 上段2
state MHighThrust3 : 上段3

state Swing : 横扫

state TripleThrust12 : 三段突刺12段
state TripleThrust3 : 三段突刺3段

state ChargeFinishThrust1 : 蓄反1段
state ChargeFinishThrust2 : 蓄反2段
state ChargeFinishThrust3 : 蓄反3段

FreeState --> MidThrust1 : acting
MidThrust1 --> FreeState : waiting

MidThrust1 --> MidThrust2 :acting
MidThrust2 --> FreeState :waiting

MidThrust2 --> MidThrust3 :acting
MidThrust3 --> FreeState :waiting

FreeState --> ContinuousState :acting
ContinuousState --> FreeState :waiting

@enduml