-- schema.sql

CREATE TABLE IF NOT EXISTS WEAPON_ACTION (
    WEAPON_ID VARCHAR(255),
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    ACTION_VALUE INT,
    ELEMENT_RATE DOUBLE,
    COMBO_OPTION_IDS VARCHAR(255)
);
